<?php
/**
 * DAO class.
 * Code Generated by the Code Generator module of ZnetDK 4 Mobile.
 */
namespace __DAO_NAMESPACE__;
class __DAO_CLASS_NAME__ extends \DAO {

    protected function initDaoProperties() {
        $this->table = '{{SQL_TABLE_NAME}}';
    }
    
    public function setFilterForSuggestions($query, $searchInColumn) {
        $this->filterClause = "WHERE {$searchInColumn} LIKE ?";
        $this->setFilterCriteria("%{$query}%");
    }
    
    public function setKeywordAsFilter($keywords, $searchInColumn) {        
        if ($this->filterClause === FALSE) {
            $this->filterClause = 'WHERE ';
        } else {
            $this->filterClause .= ' AND ';
        }
        $searchedKeywords = explode(',', $keywords);
        foreach ($searchedKeywords as $key => $value) {
            if ($key === 0) {
                $this->filterClause .= '(';
            } else {
                $this->filterClause .= ' OR ';
            }
            $this->filterClause .= "{$searchInColumn} LIKE ?";
            $this->filterValues[] = "%{$value}%";
            if ($key+1 === count($searchedKeywords)) {
                $this->filterClause .= ')';
            }
        }
    }

}