<?php
/**
 * App Menu entry.
 * Code Generated by the Code Generator module of ZnetDK 4 Mobile.
 * The line below is to insert into the 'menu.php' script of the application.
 */
\MenuManager::addMenuItem(NULL, '{{VIEW_NAME}}', '{{VIEW_LABEL}}', 'fa-{{VIEW_ICON}}');
